- hosts: localhost
  vars_prompt:
    - name: ssh_email
      prompt: Enter your email for the ssh key
      private: false
    - name: ssh_passphrase
      prompt: Enter a passphrase for the ssh key
  pre_tasks:
    - name: Upgrade system packages and cache
      become: true 
      community.general.pacman:
        update_cache: true
        upgrade: true
  tasks:
    - name: Create aur_builder user
      become: true
      ansible.builtin.user:
        name: aur_builder
        create_home: true
        group: wheel
    - name: Allow aur_builder user to run sudo pacman without a password
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: true
        validate: 'visudo -cf %s'
    - name: Setting up system
      include_tasks: "{{ task }}"
      loop:
        - tasks/core-install.yml
        - tasks/core-setup.yml
        - tasks/lsp-install.yml
        - tasks/nvim-setup.yml
      loop_control:
        loop_var: task
