- hosts: localhost
  pre_tasks:
    - name: Upgrade system packages and cache
      become: true 
      community.general.pacman:
        update_cache: true
        upgrade: true
  tasks:
    - name: Create aur_builder user
      become: true
      ansible.builtin.user:
        name: aur_builder
        create_home: true
        group: wheel
    - name: Allow aur_builder user to run sudo pacman without a password
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: true
        validate: 'visudo -cf %s'
    - name: Fetch tasks list
      become: false
      register: tasks 
      ansible.builtin.find:
        paths: ./tasks
        recurse: no
        file_type: file
    - name: Setting up system
      include_tasks: "{{ task.path }}"
      loop: "{{ tasks.files }}"
      loop_control:
        loop_var: task
