- name: Install package manager paru
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: paru
    use: makepkg
    state: present
- name: Install system packages 1/3 - xorg, xorg-server, xorg-xinit, stow, ripgrep
  become: true
  community.general.pacman:
    name:
      - xorg
      - xorg-server
      - xorg-xinit
      - stow
      - ripgrep
- name: Install system packages 2/3 - git, network-manager-applet, zsh, tmux, alacritty
  become: true
  community.general.pacman:
    name:
      - git 
      - network-manager-applet
      - zsh
      - tmux
      - alacritty
- name: Install system packages 3/3 - i3-wm, polybar, rlaunch, feh, maim, xclip
  become: true 
  become_user: aur_builder
  kewlfft.aur.aur:
    use: paru
    state: present
    name:
      - i3-wm
      - polybar-git
      - rlaunch
      - feh
      - maim
      - xclip
- name: Install ibm plex mono
  become: true 
  become_user: aur_builder
  kewlfft.aur.aur:
    use: paru
    state: present
    name: ttf-ibm-plex
