draw_bold_text_with_bright_colors: true

window:
  dynamic_padding: true

font:
  normal:
    family: IBM Plex Mono
    style: Regular
  bold:
    family: IBM Plex Mono
    style: Bold
  italic:
    family: IBM Plex Mono
    style: Italic
  bold_italic:
    family: IBM Plex Mono
    style: Bold Italic

  size: 6

# Colors
colors:
  # Default colors
  primary:
    background:        '#080808'
    foreground:        '#b2b2b2'
    bright_foreground: '#eeeeee'

  # Cursor colors
  cursor:
    text:   '#080808'
    cursor: '#9e9e9e'

  # Selection colors
  selection:
    text:       '#080808'
    background: '#b2ceee'

  # Normal colors
  normal:
    black:   '#323437'
    red:     '#ff5454'
    green:   '#8cc85f'
    yellow:  '#e3c78a'
    blue:    '#80a0ff'
    magenta: '#d183e8'
    cyan:    '#79dac8'
    white:   '#c6c6c6'

  # Bright colors
  bright:
    black:   '#949494'
    red:     '#ff5189'
    green:   '#36c692'
    yellow:  '#c2c292'
    blue:    '#74b2ff'
    magenta: '#ae81ff'
    cyan:    '#85dc85'
    white:   '#e4e4e4'
